spring:
  profiles:
    active: dev
  application:
    name: landscape-community
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.225.84:8848
        enabled: true
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8082