spring:
  datasource:
    hikari:
      username: ENC(2W4KOuK9M0+NVj//ImFK5ON+KEVquexg)
      password: ENC(DUnsZiececSVj887XG25EKcE6n8mEKYAnvDMX8sBZN0=)
    url: jdbc:mysql://rm-m5e7m812mtoyld478.mysql.rds.aliyuncs.com:3306/lexin?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
