spring:
  profiles:
    active: STAGING
  application:
    name: landscape-user
  smile-boot:
    trace-logger:
      log-path: relative:log
      log-file-name: event
      pattern: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  cloud:
    nacos:
      discovery:
        server-addr: 47.107.225.84:8848
        enabled: true
#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8081